### ISSUE TITLE
Configurable background

### ISSUE THREAD

**Issue by DEVNULLDNE** [KazuAlex/firefox-new-tab-page-container#1]
Good extensions very useful.  It burns my eyes every time I open it though.  I would really like a black background.

**Comment by KazuAlex** [comment]
Hey!
Dark mode will come with a full code refactoring :D
I'll try to work on it this week or next
Stay tuned :)

**Comment by KazuAlex** [comment]
Here is a screenshot for future dark mode 😉 i've pushed the code in v3 branch but I'm not really satisfied by the color scheme 
![image](https://user-images.githubusercontent.com/7015549/142803919-2174da39-6f88-4538-9172-301bbceadc47.png)

(If a UI designer sees this, let me know 😄)

**Comment by KazuAlex** [comment]
The new version has been submitted to AMO. Waiting for review ;)

**Comment by DEVNULLDNE** [comment]
I think it's great.  Very functional, which is a very underappreciated art. Thanks for your work.

**Comment by KazuAlex** [comment]
New version has been approved ! :D
