### ISSUE TITLE
FR: Filter by prefix

### ISSUE THREAD

**Issue by Lockszmith-GH** [KazuAlex/firefox-new-tab-page-container#3]
I use [Temporary Containers](https://github.com/stoically/temporary-containers) [extension](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) in auto-mode, this generates quite a lot of tmpXXXX containers on the fly (it also cleans them up eventually).

This page is awesome, but I wish I could filter out everything starting with tmp.

**Comment by KazuAlex** [comment]
Hi @Lockszmith-GH 
I'm working on a complete rewriting of the extension with a lot of customization.
And your idea is really good. I'll do it.

**Comment by KazuAlex** [comment]
New release with this setting!
https://github.com/KazuAlex/firefox-new-tab-page-container/releases/tag/4.0.0 :)
